# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "ndc_lsp"
edition.workspace = true
version.workspace = true

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
ndc_lib.workspace = true
tower-lsp.workspace = true

